# Generated by Django 2.0.1 on 2018-01-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1s', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pussy',
            options={'verbose_name_plural': 'pussyplays'},
        ),
    ]
